//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pract2Unidad3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PELICULA
    {
        public int Codigo { get; set; }
        public string Titulo { get; set; }
        public string Director { get; set; }
        public string AutorPrincipal { get; set; }
        public Nullable<int> No_Actores { get; set; }
        public Nullable<double> Duracion { get; set; }
        public Nullable<int> Estreno { get; set; }
    }
}
